from django.db import models
import mongoengine
class jdprice(mongoengine.Document):
    url = mongoengine.StringField(default=None)
    source=mongoengine.StringField(default=None)
    name = mongoengine.StringField(default=None)
    price = mongoengine.StringField(default=None)
    shop = mongoengine.StringField(default=None)
    date = mongoengine.StringField(default=None)
class tbprice(mongoengine.Document):
    url = mongoengine.StringField(default=None)
    source = mongoengine.StringField(default=None)
    name = mongoengine.StringField(default=None)
    price = mongoengine.StringField(default=None)
    shop = mongoengine.StringField(default=None)
    date = mongoengine.StringField(default=None)
class tmallprice(mongoengine.Document):
    url = mongoengine.StringField(default=None)
    source = mongoengine.StringField(default=None)
    name = mongoengine.StringField(default=None)
    price = mongoengine.StringField(default=None)
    shop = mongoengine.StringField(default=None)
    date = mongoengine.StringField(default=None)
class sgeprice(mongoengine.Document):
    source=mongoengine.StringField(default=None)
    date = mongoengine.StringField(default=None)
    Au95 = mongoengine.StringField(default=None)
    Au99 = mongoengine.StringField(default=None)
    Au100 = mongoengine.StringField(default=None)
    iAu99 = mongoengine.StringField(default=None)
    AuTD = mongoengine.StringField(default=None)
    AuTN1 = mongoengine.StringField(default=None)
    AuTN2 = mongoengine.StringField(default=None)
    mAuTD = mongoengine.StringField(default=None)
    Pt95 = mongoengine.StringField(default=None)
    Ag99 = mongoengine.StringField(default=None)
    AgTD = mongoengine.StringField(default=None)
    PGC = mongoengine.StringField(default=None)
class sgejrhq(mongoengine.Document):
    title=mongoengine.StringField(default=None)
    date = mongoengine.StringField(default=None)
    Au95 = mongoengine.StringField(default=None)
    Au99 = mongoengine.StringField(default=None)
    Au100 = mongoengine.StringField(default=None)
    iAu99 = mongoengine.StringField(default=None)
    AuTD = mongoengine.StringField(default=None)
    AuTN1 = mongoengine.StringField(default=None)
    AuTN2 = mongoengine.StringField(default=None)
    mAuTD = mongoengine.StringField(default=None)
    Pt95 = mongoengine.StringField(default=None)
    Ag99 = mongoengine.StringField(default=None)
    AgTD = mongoengine.StringField(default=None)
    PGC = mongoengine.StringField(default=None)
class tmallinfo(mongoengine.Document):
    shop = mongoengine.StringField(default=None)
    date = mongoengine.StringField(default=None)
    info = mongoengine.StringField(default=None)
class jdinfo(mongoengine.Document):
    shop = mongoengine.StringField(default=None)
    date = mongoengine.StringField(default=None)
    info = mongoengine.StringField(default=None)